language: node_js
node_js:
- '6'
before_install:
- npm i npm-cli-login -g
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "AcGYwU1Y29OYU5ok3zFhS1vvSAxBITDTJY6dsU6fX0SJaJwlhoOOSe2SVlEV28kUFvBGGE7rekDeRSZmDOSceBDm7bW7zF8nY5xdfrIdJNClwO0zBeavwb4H2a3gV2EHDOZdtQWzz5h4d/EBPVa0Cwfi6zzBbzjeOJoiaa3s5AoFadCPBN5TfoWH2DryPD9tT7kNRxsGvkbZ4wNn/xFp7PungZucoKElhNVvXchDeU3GtKaIng+afZ4s2IN/7+Qgw7i160+p2rN4r3uhJ7ldmQaUFnLD9FNnhat2xxSH0OA7nJgRxFIstBYfFu8zfhq+ZVK3QngA6C1fclxFhV0iMlfcB43HZvySmmZ3CUDPKMBvjVRd2QRL8k07agAhVorPiOmczKqybG2cs5icduUwRF6lIHfIuM5Yyho2P7sitM2Rtz36MmjMR4k2ciS6MfSCR7PmUJLFHtbiPbMyZzJaWCQvE8Ib1dXN846Cho9rEsrxiTultH0+gPWWqm1RMQkZZ1fawL7OghIBCSn9FdrF8gQl6Zj8+So3Rrisj6IC/PUd/WjRw1baNz/DbCT0+5xeAbp+5PqrptrMaiMwAZ1ARvLDQtFRrmLjs6c8RbwJNwG6Dsa1Pytx/mzT5yePlYaeofX7PP94p1dbGOguXoSjwNXMGwFiUTpF1c1C2w182co="
env:
  secure: "LcgahYhmI1voj5pSRj2iA3UJJdRGTmHWdrYwffvFlReatYfoid2vuqKwdJKcpK0OSgvgoYwkBcgA0TORDWTaZAo+oYslLg3U1IEKbFSj+rT4GLzlLZjbwvYkIek9EtVAk71YtJ2wQqIpvF0Mtu5w2Vp+I/4JG1aaEqezO+tBJIRkjazyLZy+6KwgoTIPn6QxcV5pKfcP+FtJ5G/eJcfvpGbqOnKDLabwpuprEXsvUfZxPFMcPnLpw7EQE0lOCA99zdetk+71MDzMcaS7we81SDRI+ECHf+M5GzY6dCkeke6N3vSBtC1uohN6HC9RDSDsAOP7xEjA+WFVKI5pyxmbr4Sjn1Clo5ZNIcBGbYhVOwHmcvp3GxGFqu5bdAwJ9ST1E5e10o+65HxHLu7MrmEcgJSZv1LgQpMS3y3+j5mCygbHz6oJeCW+e9W/gOcCpL5fZ+r8rSzFS+5SilXirkP4+W+nT+ITHopbzCNns65aS7bd9ncHrMPFqkLHp6lDc1TT4KnHv9oD6KIJSx51VtSyIglzfNQDg+WDZarM5+cdc2Z/NWa7hQOFPnw21G098USRNV3/uznyUUg3ykIH6gg74xFsP1VXvKCZx91k70E3Qvb7sO6sjGvohxrGBSQcIHcaFctq527D/HslbvqiN33h/z8mKpH46txFcicYFARhSL8="
